### ISSUE TITLE
In the case of multithreading, there are pits, resulting in segment errors

### ISSUE THREAD

**Issue by coolzhangfeng** [KjellKod/g3sinks#116]
**Describe the bug**
In the case of multithreading, there are pits, resulting in segment errors

**To Reproduce**
ubuntu16 aarch64

**Additional context**
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:90                                             
#1  0x000055555597da53 in g3::LogMessage::LogMessage(g3::LogMessage const&) ()                                                     
#2  0x0000555555968571 in g3::LogWorkerImpl::bgSave(g3::MoveOnCopy<std::unique_ptr<g3::LogMessage, std::default_delete<g3::LogMessage> > >) ()                                                                                                                        
#3  0x00005555559688e3 in std::_Function_handler<void (), g3::LogWorker::save(g3::MoveOnCopy<std::unique_ptr<g3::LogMessage, std::default_delete<g3::LogMessage> > >)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()                                             
#4  0x00005555554d0665 in std::function<void ()>::operator()() const (this=0x7ffff477bd90) at /usr/include/c++/5/functional:2267   
#5  0x000055555568fdbe in kjellkod::Active::run (this=0x555555e6cf00)                                                              
    at /squirrel/examples/dispatch_gateway/squirrel_framework/projects/mds/mdc_host/../../../third_party_x86/g3log-1.3.4/include/g3log/active.hpp:40                                                                                                                  
#6  0x00005555556b3d4e in std::_Mem_fn_base<void (kjellkod::Active::*)(), true>::operator()<, void>(kjellkod::Active*) const (     
    this=0x555555e6d260, __object=0x555555e6cf00) at /usr/include/c++/5/functional:600

**Comment by KjellKod** [comment]
Hi 

not sure what you are referring to. If you have found an issue in the code please explain it. 

The section: “to reproduce” 
doesn’t really explain a whole lot, especially since this code is running on Linux 64 bit systems for years on probably thousands on systems 

For a crash during multithreaded execution it’s not unusual to see the g3log’s code show up. That doesn’t necessarily mean that the issue is in g3log’s multithreading but rather that this was ALSO executing when the seg default (or similar) happened on the system. 

This can be confusing of course but the stack dumps are bound to the information given to them. 

Two examples of when stackdumps such as this could show up would be when initialization of G3log is done in a bad way 
by the dev. 

1. When initialized in a library and not in the “main” executable. All platforms (nix, OSX, Windows) have undefined behavior for several threaded constructs if this is done — most devs don’t know about this and this is a common issue. 
2. When initialized first and then later the process is forked. This is the most insidious issue as your setup could work for months until you do some inocous, not related to multi threading, and all of a sudden the threaded construct start giving segmentation errors 


My advice is that you:
1. Search the previously solved issues and see if your initialization suffers from a similar issue 
2. Check the examples and doc and verify that your initialization  is not suffering from what I describe  above
3. Try to isolate the issue in a minimalistic example (vs saying Ubuntu 64-bit) that you can share with the community so that other people can help you figure out the issue. 


I’m not saying it’s impossible that this issue isn’t a bug with G3log. I’m saying it’s more likely it’s an issue with the initialization or code outside of G3log.

**Comment by coolzhangfeng** [comment]
I'm sure it's initialized from the beginning,G3log is used in many of our projects and performs well.but this problem occurs in multithreaded projects.
Interestingly, we do not have this problem with version 1.3.1, but only with version 1.3.4

**Comment by KjellKod** [comment]
Maybe this issue should be opened on G3log then and not g3sinks?

**Comment by KjellKod** [comment]
G3log 1.3.1 was the last version that supported C++11. 

After 1.3.1 the system setup must support C++14.  There will be C++ language or standard language changes on 1.3.4 that will likely cause undefined behavior (ideally not compile) on a C++11 only supported compiler.

**Comment by KjellKod** [comment]
@coolzhangfeng is this issue resolved? If so please provide resolution for other folks in the community. 

I’m flagging this issue to be closed since there’s been no activity for a month
